apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: job-processing
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: db-init
        configMap:
          name: db-init
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: jobqueue
        - name: POSTGRES_USER
          value: jobuser
        - name: POSTGRES_PASSWORD
          value: jobpass123
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
